#!/bin/bash
cp ./mbafan.py /usr/bin
cp mbafan.service /lib/systemd/system/
chmod +x /usr/bin/mbafan.py
systemctl enable mbafan
systemctl start mbafan
state=$(cat /sys/devices/platform/applesmc.768/fan1_manual)
if [ $state -eq 1 ]
then
    echo 'All good. (hopefully)'
else
    echo 'Error, probably restarting it will fix it.'
fi
